; Script generated by Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "WebMouse Helper"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "WebMouse"
#define MyAppURL "https://webmouse.app"
#define MyAppExeName "webmouse_helper.py"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
AppId={{D37F21F5-3850-4E86-A06D-64C4D1168B50}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\WebMouseHelper
DisableProgramGroupPage=yes
OutputBaseFilename=WebMouseHelperSetup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "startupicon"; Description: "Start WebMouse Helper automatically when Windows boots"; GroupDescription: "Startup Options:"

[Files]
Source: "webmouse_helper.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "run_helper.bat"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\run_helper.bat"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\run_helper.bat"; Tasks: desktopicon
Name: "{commonstartup}\{#MyAppName}"; Filename: "{app}\run_helper.bat"; Tasks: startupicon

[Run]
Filename: "{app}\run_helper.bat"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: shellexec postinstall nowait
